name: Docker Image CI

on:
  push:
    branches: [ 2.0-dev ]
  pull_request:
    branches: [ 2.0-dev ]
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      JF_URL: ${{ secrets.JF_URL }}
      # JFrog Platform access token
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JFROG_BUILD_STATUS: PASS

    steps:
    - name: Step1 - Checkout
      uses: actions/checkout@v3
      
    # setup JFrog CLI
    - name: Step2 -  Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2
    
    # Verify artifactory conenctivity
    - name: Step2 - Ping RT
      run: |
        # Ping the server
        jf rt ping
      
    - name: Step4 - Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER }}/petclinic-docker-dev-virtual/petclinic:${{github.run_number}}
      
    - name: Step5 - Push Docker image
      run: |
        echo ${{ secrets.DOCKER }}
        jf rt dp ${{ secrets.DOCKER }}/petclinic-docker-dev-virtual/petclinic:${{github.run_number}} petclinic-docker-dev-virtual
    
    - name: Step6- Failure check
      run: |
        echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
      if: failure()
      
    - name: Step7 - Publish to RT
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        # Add env vars
        jf rt bce

        # Collect VCS details from git and add them to the build
        jfrog rt bag
        
        # Publish build-info
        jf rt bp
    - name: Step8 - Xray Scan
      run: |
        jf rt bs --fail=false
        
    - name: Step9 - Docker Promote
      run: |
        jf rt --copy bpr petclinic-docker-prod-local
    
