# This is a basic workflow to help you get started with Actions

name: Gihub Actions Maven Build Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JF_URL: ${{ secrets.JF_URL }}
      # JFrog Platform access token
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JFROG_BUILD_STATUS: PASS

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # setup JFrog CLI
      - name: Step 1-  Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 2-  Checkout main branch from Github
        uses: actions/checkout@v2

      # Setup JDK 1.8
      - name: Step3 - Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Verify artifactory conenctivity
      - name: Step4 - Ping RT
        run: |
          # Ping the server
          jfrog rt ping

      - name: Step5- Run Maven build
        env:
          SERVER_ID: ${{ secrets.MY_ARTIFACTORY_SERVER_ID }}
        run: |
          # Init JFrog CLI Maven config
          MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`

          # Make sure artifactory servers for resolving 3rd party dependencies and for deploy are known to JFrog CLI
          jfrog rt mvn-config --server-id-resolve=$SERVER_ID --server-id-deploy=$SERVER_ID --repo-resolve-releases=avi-maven-release-virtual --repo-resolve-snapshots=avi-maven-snapshot-virtual --repo-deploy-releases=avi-maven-release-virtual --repo-deploy-snapshots=avi-maven-snapshot-virtual                                                                                                                                                                                                                                                                                                 
          
          # Build the maven project ( see https://www.jfrog.com/confluence/display/JFROG/Setting+Up+CI+Integration)
          jfrog rt mvn clean install

      - name: Step6- Failure check
        run: |
          echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
        if: failure()

      
      - name: Step7 - Publish to RT
        env: 
          GITHUB_TOKEN: ${{secrets.VC_TOKEN}}
        run: |
          # Add env vars
          jfrog rt bce

          # Collect VCS details from git and add them to the build
          jfrog rt bag

          #Publish build-info
          jfrog rt bp

          # Prerequisite to xray scan a build
          # 1. Make sure this build is indexed in Admin->Xray->Settings->Indexed Resources->Builds tab
          # ( see https://jfrog.com/knowledge-base/xray-how-to-index-and-scan-all-builds-in-xray-in-the-unified-platform/ )
          # 2. A watch on the build resource is defined and mapped to a policy that has he policy has  option "fail on build" selected 
          # (see https://stackoverflow.com/questions/55992256/xray-scan-does-not-find-any-watch-when-launched-from-azure-devops-pipeline
          # and https://www.jfrog.com/confluence/display/JFROG/CI-CD+Integration+with+Xray )
          # 3. Scan build with JFrog Xray and if you do not want the build to fail use "--fail=false" 
          # ( see https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-ScanningaPublishedBuild)
          jfrog rt bs --fail=false
